### ISSUE TITLE
Implement ari.connect timeout

### ISSUE THREAD

**Issue by litnimax** [asterisk/ari-py#13]
Hi guys!
I miss timeout parameter in ari.connect method.
In case of routing issues connect takes too much time.
Is it possible to have a timeout=x param?
Thanks.

**Comment by matt-jordan** [comment]
I think a timeout parameter would be fine. Would you mind making a pull request for it?

**Comment by litnimax** [comment]
I looked though ari code and did not see a simple way to add timeout param for connect.
May be somebody from original developers? :-)

**Comment by matt-jordan** [comment]
I doubt any of us are going to perform a pull request for that any time soon.
