### ISSUE TITLE
No module named 'client'

### ISSUE THREAD

**Issue by damienstanton** [asterisk/ari-py#14]
Getting this error on Ubuntu 14.04LTS running Python 3.4.0 in a virtual environment.
Traceback is:

``` bash
>>> import ari
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/user/project/env/lib/python3.4/site-packages/ari-0.1.3-py3.4.egg/ari/__init__.py", line 8, in <module>
ImportError: No module named 'client'
```

This occurs whether installing from source/setup.py or PyPi.

**Comment by damienstanton** [comment]
I recreated my development environment in another virtualenv running Python 2.7.6 and the issue does not occur. If this is simply a case of 3.x not being supported, the documentation should be updated to make this clear.

**Comment by leedm777** [comment]
I've fixed that specific issue, but I'm sure there are more problems that you'll run into with Python 3.

I put a note in the TODO section for adding Python 3 support. If you have any experience using 2to3, suggestions on how to add that are welcome (my first attempt at simply putting `use_2to3 = True` in `setup.py` didn't seem to do anything).

Thanks for the feedback!

**Comment by damienstanton** [comment]
Glad to help. I'm running 2to3 against the source dir now in fact, and starting to parse the output. I will let you know if I make headway on it!

**Comment by sunbeibei-hub** [comment]
i need it， too。。。。。。help~
