### ISSUE TITLE
ari-py application/callback not receiving StasisStart and StasisEnd events

### ISSUE THREAD

**Issue by SonnyRajagopalan** [asterisk/ari-py#15]
Hello,

I am following the tutorial in https://wiki.asterisk.org/wiki/display/AST/Introduction+to+ARI+and+Channels and have downloaded and installed https://github.com/asterisk/ari-py in my system. I am able to interact with ARI using `wscat` per https://wiki.asterisk.org/wiki/display/AST/Getting+Started+with+ARI and I see channel creation/state change/deletion notifications that in the `wscat` log. However, when I run `channel-dump.py` in another terminal in the same machine (connecting to `http://localhost:8088` like the tutorial), I do not see the channel creation, deletion and state modification messages. The only message I see are either `No channels currently :-(` or, if I have a current channel running, and then I fire up `channel-dump.py`, I see the current channel information. However, I do not see the notification when I hang up the same call. I think this is due to the fact that the event callbacks in `ari-py`, specifically the lines:

```
client.on_channel_event('StasisStart', stasis_start_cb)
client.on_channel_event('StasisEnd', stasis_end_cb)[/code]
```

don't seem to work.

Any ideas on how to fix this is appreciated.

**Comment by SonnyRajagopalan** [comment]
I figured out the problem. The issue was in the `channel-dump.py` code in the aforementioned wiki. They line should end like so:

```
client.run(apps='hello-world')
```

and **not** like

```
client.run(apps='channel-dump')
```

**Comment by matt-jordan** [comment]
Hi!

I took a look at the wiki page, and actually, it _should_ be channel-dump. The application your WebSocket says it can handle should match the application argument passed to the Stasis dialplan application. On the wiki page you linked, the dialplan passes 'channel-dump' to the Stasis application:

```
[default]

exten => 1000,1,NoOp()
 same =>      n,Answer()
 same =>      n,Stasis(channel-dump)
 same =>      n,Hangup()
```

I'm guessing you kept the dialplan from the previously 'hello-world' example, which would cause the behaviour you saw.

**Comment by SonnyRajagopalan** [comment]
Agreed, I discovered this as well, but failed to note it here. Thanks for clarifying it here as well.

**Comment by AnnemPranitha** [comment]
Hi Experts,

I have used the below dial plan  

[default]

exten => 1000,1,NoOp()
 same =>      n,Answer()
 same =>      n,Stasis(channel-dump)
 same =>      n,Hangup()

After starting asterisk, and running channel-dump.py from another terminal tired to make a call to the extension 1000. Here i am facing the error  like channel-dump not registered.
snip>>>>
 ERROR[14846][C-00000000]: res_stasis.c:1247 stasis_app_exec: Stasis app 'channel-dump' not registered

Please provide your inputs to resolve the issue.
