### ISSUE TITLE
Error determining real directory for rest-api

### ISSUE THREAD

**Issue by goseeped** [asterisk/ari-py#20]
After installing "ari-api"  i try to run this example.

```
import ari

client = ari.connect('http://localhost:8088/', 'asterisk', 'asterisk')

def on_dtmf(channel, event):
    digit = event['digit']
    if digit == '#':
        channel.play(media='sound:goodbye')
        channel.continueInDialplan()
    elif digit == '*':
        channel.play(media='sound:asterisk-friend')
    else:
        channel.play(media='sound:digits/%s' % digit)


def on_start(channel, event):
    channel.on_event('ChannelDtmfReceived', on_dtmf)
    channel.answer()
    channel.play(media='sound:hello-world')


client.on_channel_event('StasisStart', on_start)
client.run(apps="hello-world")
```

Immediately i get this error:

`ERROR[7041]: res_ari.c:605 ast_ari_get_docs: Error determining real directory for rest-api.`

asterisk version: 13.7.2

Maybe something related with "swaggerpy" ??

-Thanks

**Comment by mouseratti** [comment]
@goseeped I had the same trouble. The reason is that there was no directory **/usr/share/asterisk/rest-api/**\* in my asterisk package(ubuntu 16.04). I downloaded a tarball with asterisk sources, copied required files from it. 
**Note!** 
You need to copy all .json files into **/usr/share/asterisk/rest-api/** from **rest-api/api-docs** directory.

**Comment by mouseratti** [comment]
@leedm777 actually, this is not an error of **ari-py**. Think, you could close this issue

**Comment by goseeped** [comment]
@mouseratti i figured out later and i forget to update this ticket anycase thanks for your time !

**Comment by marco-budiongan** [comment]
https://downloads.asterisk.org/pub/telephony/asterisk/asterisk-13-current.tar.gz
https://downloads.asterisk.org/pub/telephony/asterisk/asterisk-14-current.tar.gz

- "I downloaded a tarball with asterisk sources, copied required files from it."
